In [17]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp312-cp312-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp312-cp312-win_amd64.whl (14.3 MB)
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/14.3 MB 1.1 MB/s eta 0:00:14
   - -------------------------------------- 0.4/14.3 MB 2.9 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/14.3 MB 4.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.3 MB 4.7 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/14.3 MB 4.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.4/14.3 MB 4.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/14.3 MB 4.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/14.3 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/14.3 MB 3.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/14.3 MB 3.8 MB/s eta 0:00:04
   ------ --------------------------------- 2.4/14.3 MB 4.1 MB/s eta 0:00:03
   ------- -------------------------------- 2.5/14.3 MB 4.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.7/14.3 MB 4.1 MB/s eta 0:00:03
   -------- ------------------------------- 2.9/14.3 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 3.1/14.3 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 3.3/14.3 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 3.5/14.3 MB 4.0 MB/s eta 0:00:03
   ---------- ----------------------------- 3.6/14.3 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 3.8/14.3 MB 3.9 MB/s eta 0:00:03
   ----------- ---------------------------- 4.0/14.3 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 4.2/14.3 MB 3.9 MB/s eta 0:00:03
   ------------ --------------------------- 4.4/14.3 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 4.5/14.3 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 4.5/14.3 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 4.9/14.3 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 5.1/14.3 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 5.3/14.3 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 5.5/14.3 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 5.7/14.3 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 5.9/14.3 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 6.0/14.3 MB 3.9 MB/s eta 0:00:03
   ----------------- ---------------------- 6.2/14.3 MB 3.9 MB/s eta 0:00:03
   ----------------- ---------------------- 6.4/14.3 MB 3.9 MB/s eta 0:00:03
   ------------------ --------------------- 6.6/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 6.8/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 7.0/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 7.1/14.3 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 7.3/14.3 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 7.5/14.3 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 7.6/14.3 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 7.9/14.3 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 8.1/14.3 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 8.3/14.3 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 8.5/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 8.7/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 8.9/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 9.1/14.3 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 9.2/14.3 MB 3.9 MB/s eta 0:00:02
   -------------------------- ------------- 9.4/14.3 MB 3.9 MB/s eta 0:00:02
   -------------------------- ------------- 9.6/14.3 MB 3.9 MB/s eta 0:00:02
   --------------------------- ------------ 9.8/14.3 MB 3.9 MB/s eta 0:00:02
   --------------------------- ------------ 10.0/14.3 MB 3.9 MB/s eta 0:00:02
   ---------------------------- ----------- 10.2/14.3 MB 3.9 MB/s eta 0:00:02
   ---------------------------- ----------- 10.4/14.3 MB 4.0 MB/s eta 0:00:01
   ----------------------------- ---------- 10.5/14.3 MB 4.0 MB/s eta 0:00:01
   ----------------------------- ---------- 10.7/14.3 MB 4.0 MB/s eta 0:00:01
   ------------------------------ --------- 10.9/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 11.1/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 11.2/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 11.5/14.3 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 11.6/14.3 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 11.8/14.3 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 12.0/14.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 12.2/14.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 12.4/14.3 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 12.6/14.3 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 12.8/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 12.9/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 13.3/14.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 13.5/14.3 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 13.6/14.3 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 13.9/14.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  14.0/14.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  14.3/14.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 14.3/14.3 MB 3.8 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [1]:
import pandas as pd
import mysql.connector
import sqlalchemy as sal
from sqlalchemy import create_engine

In [3]:
df = pd.read_csv('netflix.csv')

In [5]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [7]:
conn = mysql.connector.connect(host="localhost",
                               user="root",
                               password="123321",
                               database="netflix")

In [9]:
engine = create_engine('mysql+mysqlconnector://root:123321@localhost/netflix')

In [13]:
df.to_sql('netflix_data', con = engine, index = False, if_exists = 'append')

IntegrityError: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 's1' for key 'netflix_data.PRIMARY'
[SQL: INSERT INTO netflix_data (show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES (%(show_id)s, %(type)s, %(title)s, %(director)s, %(cast)s, %(country)s, %(date_added)s, %(release_year)s, %(rating)s, %(duration)s, %(listed_in)s, %(description)s)]
[parameters: [{'show_id': 's1', 'type': 'Movie', 'title': 'Dick Johnson Is Dead', 'director': 'Kirsten Johnson', 'cast': None, 'country': 'United States', 'date_added': 'September 25, 2021', 'release_year': 2020, 'rating': 'PG-13', 'duration': '90 min', 'listed_in': 'Documentaries', 'description': 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'}, {'show_id': 's2', 'type': 'TV Show', 'title': 'Blood & Water', 'director': None, 'cast': 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mah ... (5 characters truncated) ... , Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng', 'country': 'South Africa', 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '2 Seasons', 'listed_in': 'International TV Shows, TV Dramas, TV Mysteries', 'description': 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'}, {'show_id': 's3', 'type': 'TV Show', 'title': 'Ganglands', 'director': 'Julien Leclercq', 'cast': 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'description': 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'}, {'show_id': 's4', 'type': 'TV Show', 'title': 'Jailbirds New Orleans', 'director': None, 'cast': None, 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'Docuseries, Reality TV', 'description': 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.'}, {'show_id': 's5', 'type': 'TV Show', 'title': 'Kota Factory', 'director': None, 'cast': 'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar', 'country': 'India', 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '2 Seasons', 'listed_in': 'International TV Shows, Romantic TV Shows, TV Comedies', 'description': 'In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.'}, {'show_id': 's6', 'type': 'TV Show', 'title': 'Midnight Mass', 'director': 'Mike Flanagan', 'cast': 'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'TV Dramas, TV Horror, TV Mysteries', 'description': 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.'}, {'show_id': 's7', 'type': 'Movie', 'title': 'My Little Pony: A New Generation', 'director': 'Robert Cullen, José Luis Ucha', 'cast': 'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'PG', 'duration': '91 min', 'listed_in': 'Children & Family Movies', 'description': "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals — and, hoof to heart, she’s determined to prove it."}, {'show_id': 's8', 'type': 'Movie', 'title': 'Sankofa', 'director': 'Haile Gerima', 'cast': 'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri', 'country': 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia', 'date_added': 'September 24, 2021', 'release_year': 1993, 'rating': 'TV-MA', 'duration': '125 min', 'listed_in': 'Dramas, Independent Movies, International Movies', 'description': 'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.'}  ... displaying 10 of 8807 total bound parameter sets ...  {'show_id': 's8806', 'type': 'Movie', 'title': 'Zoom', 'director': 'Peter Hewitt', 'cast': 'Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers', 'country': 'United States', 'date_added': 'January 11, 2020', 'release_year': 2006, 'rating': 'PG', 'duration': '88 min', 'listed_in': 'Children & Family Movies, Comedies', 'description': 'Dragged from civilian life, a former superhero must train a new crop of youthful saviors when the military preps for an attack by a familiar villain.'}, {'show_id': 's8807', 'type': 'Movie', 'title': 'Zubaan', 'director': 'Mozez Singh', 'cast': 'Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy', 'country': 'India', 'date_added': 'March 2, 2019', 'release_year': 2015, 'rating': 'TV-14', 'duration': '111 min', 'listed_in': 'Dramas, International Movies, Music & Musicals', 'description': "A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past."}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)